=== evillage/clang-magento2-integration/Clang/etc/template_endpoints.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="templates">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="template" type="template" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="template">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="endpoint" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== evillage/clang-magento2-integration/Clang/etc/template_endpoints.xml
<?xml version="1.0" ?>
<templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="template_endpoints.xsd">
    <template>
        <name>sales_email_order_template</name>
        <endpoint>order</endpoint>
    </template>
    <template>
        <name>sales_email_order_guest_template</name>
        <endpoint>order</endpoint>
    </template>
    <template>
        <name>sales_email_order_comment_template</name>
        <endpoint>order-comment</endpoint>
    </template>
    <template>
        <name>sales_email_order_comment_guest_template</name>
        <endpoint>order-comment</endpoint>
    </template>
    <template>
        <name>sales_email_invoice_template</name>
        <endpoint>invoice</endpoint>
    </template>
    <template>
        <name>sales_email_invoice_guest_template</name>
        <endpoint>invoice</endpoint>
    </template>
    <template>
        <name>sales_email_invoice_comment_template</name>
        <endpoint>invoice-comment</endpoint>
    </template>
    <template>
        <name>sales_email_invoice_comment_guest_template</name>
        <endpoint>invoice-comment</endpoint>
    </template>
    <template>
        <name>sales_email_creditmemo_template</name>
        <endpoint>creditmemo</endpoint>
    </template>
    <template>
        <name>sales_email_creditmemo_guest_template</name>
        <endpoint>creditmemo</endpoint>
    </template>
    <template>
        <name>sales_email_creditmemo_comment_template</name>
        <endpoint>creditmemo-comment</endpoint>
    </template>
    <template>
        <name>sales_email_creditmemo_comment_guest_template</name>
        <endpoint>creditmemo-comment</endpoint>
    </template>
    <template>
        <name>sales_email_shipment_template</name>
        <endpoint>shipment</endpoint>
    </template>
    <template>
        <name>sales_email_shipment_guest_template</name>
        <endpoint>shipment</endpoint>
    </template>
    <template>
        <name>sales_email_shipment_comment_template</name>
        <endpoint>shipment-commment</endpoint>
    </template>
    <template>
        <name>sales_email_shipment_comment_guest_template</name>
        <endpoint>shipment-commment</endpoint>
    </template>
    <template>
        <name>newsletter_subscription_success_email_template</name>
        <endpoint>newsletter-subscribe</endpoint>
    </template>
    <template>
        <name>customer_create_account_email_no_password_template</name>
        <endpoint>create-account-no-password</endpoint>
    </template>
    <template>
        <name>customer_password_forgot_email_template</name>
        <endpoint>customer-password-forgot</endpoint>
    </template>
    <template>
        <name>customer_create_account_email_template</name>
        <endpoint>customer-create-account</endpoint>
    </template>
    <template>
        <name>customer_password_remind_email_template</name>
        <endpoint>customer-password-remind</endpoint>
    </template>
    <template>
        <name>newsletter_subscription_un_email_template</name>
        <endpoint>newsletter-unsubscribe</endpoint>
    </template>
    <template>
        <name>sendfriend_email_template</name>
        <endpoint>sendfriend</endpoint>
    </template>
    <template>
        <name>update_customer_template</name>
        <endpoint>update-customer</endpoint>
    </template>
    <template>
        <name>wishlist_email_email_template</name>
        <endpoint>wishlist</endpoint>
    </template>
    <template>
        <name>customer_account_information_change_email_template</name>
        <endpoint>customer-change-email</endpoint>
    </template>
</templates>
